version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: khanmotors_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - khanmotors-network

  backend:
    build: ./backend
    container_name: khanmotors_backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/khanmotors
      - PORT=5000
    depends_on:
      - mongo
    networks:
      - khanmotors-network

  admin-dashboard:
    build: 
      context: ./admin-dashboard
      args:
        VITE_SUPABASE_URL: https://addcixpchvbgykkkianm.supabase.co
        VITE_SUPABASE_ANON_KEY: sb_publishable_5qJdaDYL3WkQTpm74UhOMA_wAREUZWD
    container_name: khanmotors_admin
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    networks:
      - khanmotors-network

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt


volumes:
  mongo-data:

networks:
  khanmotors-network:
    driver: bridge
