version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: khanmotors_mongo
    restart: always
    command: ["mongod", "--wiredTigerCacheSizeGB", "0.25"]
    deploy:
      resources:
        limits:
          memory: 512M
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
    networks:
      - khanmotors-network

  backend:
    build: ./backend
    container_name: khanmotors_backend
    restart: always
    command: npm start
    deploy:
      resources:
        limits:
          memory: 512M
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/khanmotors
      - PORT=5000
      - NODE_ENV=production
      - NODE_OPTIONS=--max-old-space-size=460
    depends_on:
      - mongo
    networks:
      - khanmotors-network

  admin-dashboard:
    build: 
      context: ./admin-dashboard
      args:
        VITE_SUPABASE_URL: https://addcixpchvbgykkkianm.supabase.co
        VITE_SUPABASE_ANON_KEY: sb_publishable_5qJdaDYL3WkQTpm74UhOMA_wAREUZWD
    container_name: khanmotors_admin
    restart: always
    deploy:
      resources:
        limits:
          memory: 128M
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    networks:
      - khanmotors-network

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt


networks:
  khanmotors-network:
    driver: bridge

volumes:
  mongo_data:
